// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8LGdlY7RcVLp8RfpI8pEnXA7XlWbhQGA',
    appId: '1:241626257761:web:5da0aa49e5bf770a544d20',
    messagingSenderId: '241626257761',
    projectId: 'akatabo-app',
    authDomain: 'akatabo-app.firebaseapp.com',
    storageBucket: 'akatabo-app.appspot.com',
    measurementId: 'G-X5ZXNJ6FHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANd7S5CAU5_hvFYXRhMJWw0bS0vTFsneU',
    appId: '1:241626257761:android:711de7d4145a66ed544d20',
    messagingSenderId: '241626257761',
    projectId: 'akatabo-app',
    storageBucket: 'akatabo-app.appspot.com',
  );
}
