name: akatabo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

  # routing
  go_router: ^6.5.2

  # urls
  url_launcher: ^6.1.10

  # internationalization and formatting
  intl: ^0.18.0

  # fonts
  google_fonts: ^4.0.3

  # animations
  animations: ^2.0.7
  animated_text_kit: ^4.2.2

  # images
  cached_network_image: ^3.2.3

  # rating bar
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
