name: akatabo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # state
  flutter_riverpod: ^2.3.5
  riverpod_annotation: ^2.1.0

  # routing
  go_router: ^6.5.7

  # urls
#  url_launcher: ^6.1.10

  # internationalization and formatting
  intl: ^0.17.0

  # fonts
  google_fonts: ^4.0.3

  # animations
  animations: ^2.0.7
  animated_text_kit: ^4.2.2

  # images
  cached_network_image: ^3.2.3

  # rating bar
  flutter_rating_bar: ^4.0.1

  # progress bar
  percent_indicator: ^4.2.3

  # unique ids
  uuid: ^3.0.7
  flextras: ^1.0.0

  # svgs
  flutter_svg: ^2.0.5
  
  # Firebase
  firebase_core: ^2.10.0

  # for firebase analytics
  firebase_analytics: ^10.2.1

  # Firebase Cloud
  cloud_firestore: ^4.5.2

  # messaging
  firebase_messaging: ^14.4.1

  # Authentication
  firebase_auth: ^4.4.2

  # google auth
  google_sign_in: ^6.1.0

  # flash toast messages
  flash: ^3.0.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  riverpod_generator: ^2.1.4
  riverpod_lint: ^1.1.6
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
